apiVersion : apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: flexcub-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deploy
  template:
    metadata:
      labels:
        app: backend-deploy
    spec:
      containers:
        - name: backend-deploy
          image: praveenraj10/k8deploy:14
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-deploy-svc
  namespace: flexcub-testing
status:
  loadBalancer: {}
spec:
  ports:
    - name: backend-deploy-svc
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: backend-deploy
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
